repos:
  - repo: https://github.com/Quantco/pre-commit-mirrors-prettier
    rev: 3.2.5
    hooks:
      - id: prettier-conda
        files: \.(md|yml|yaml)$
  - repo: https://github.com/Quantco/pre-commit-mirrors-pre-commit-hooks
    rev: 4.6.0
    hooks:
      - id: trailing-whitespace-conda
      - id: end-of-file-fixer-conda
      - id: check-merge-conflict-conda
        args: ["--assume-in-merge"]
  - repo: https://github.com/Quantco/pre-commit-mirrors-typos
    rev: 1.24.5
    hooks:
      - id: typos-conda
  - repo: https://github.com/Quantco/pre-commit-mirrors-clang-format
    rev: 18.1.8
    hooks:
      - id: clang-format-conda
