# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

galeShapleyMatching <- function(prefM, uW) {
    .Call('matchingR_galeShapleyMatching', PACKAGE = 'matchingR', prefM, uW)
}

sortIndex <- function(u) {
    .Call('matchingR_sortIndex', PACKAGE = 'matchingR', u)
}

checkStability <- function(uM, uW, proposals, engagements) {
    .Call('matchingR_checkStability', PACKAGE = 'matchingR', uM, uW, proposals, engagements)
}

