name: Test Package
on: [push]
jobs:
  build-linux:
    name: CI
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          miniforge-version: latest
          miniforge-variant: Mambaforge
          channels: conda-forge
      - shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort
      - shell: bash -l {0}
        run: |
          mamba env create
          source $CONDA/bin/activate matchingR
          R CMD build .
          R CMD INSTALL matchingR_*.tar.gz
          _R_CHECK_CRAN_INCOMING_=false R CMD check --as-cran --no-vignettes --no-manual matchingR_*.tar.gz
          if cat matchingR.Rcheck/00check.log | grep -q "WARNING"; then
            echo "Found warnings, treated as errors."
            exit 1
          fi
